######################################################################
# Automatically generated by qmake (3.0) Wed Jul 16 10:42:50 2014
######################################################################

TEMPLATE = app
TARGET = easyCoding
INCLUDEPATH += . view control model

# Input
HEADERS += control/codeManager.h \
           model/code.h \
           view/codeSettings.h \
           view/easycoding.h \
           view/mainWidget.h
SOURCES += main.cpp \
           control/codeManager.cpp \
           model/code.cpp \
           view/codeSettings.cpp \
           view/easycoding.cpp \
           view/mainWidget.cpp
QT += widgets
