######################################################################
# Automatically generated by qmake (3.0) Fri Jul 18 19:57:02 2014
######################################################################

TEMPLATE = app
TARGET = fastQDA
INCLUDEPATH += . view control model

# Input
HEADERS += control/codeManager.h \
           model/code.h \
           view/codeList.h \
           view/codeSettings.h \
           view/documentList.h \
           view/fastqda.h \
           view/mainWidget.h
SOURCES += main.cpp \
           control/codeManager.cpp \
           model/code.cpp \
           view/codeList.cpp \
           view/codeSettings.cpp \
           view/documentList.cpp \
           view/fastqda.cpp \
           view/mainWidget.cpp
QT += widgets
