######################################################################
# Automatically generated by qmake (3.0) Wed Jul 16 13:37:06 2014
######################################################################

TEMPLATE = app
TARGET = fastQDA
INCLUDEPATH += . view control model

# Input
HEADERS += control/codeManager.h \
           model/code.h \
           view/codeSettings.h \
           view/fastqda.h \
           view/mainWidget.h
SOURCES += main.cpp \
           control/codeManager.cpp \
           model/code.cpp \
           view/codeSettings.cpp \
           view/fastqda.cpp \
           view/mainWidget.cpp
QT += widgets
