#############################################################################
# Makefile for building: fastQDA.app/Contents/MacOS/fastQDA
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  fastQDA.pro
# Template: app
# Command: /Users/michaelriedel/Qt/5.3/clang_64/bin/qmake -o Makefile fastQDA.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../Qt/5.3/clang_64/mkspecs/macx-clang -I. -I. -Iview -Icontrol -Imodel -I../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/AGL.framework/Headers -F/Users/michaelriedel/Qt/5.3/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/michaelriedel/Qt/5.3/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/michaelriedel/Qt/5.3/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		control/codeManager.cpp \
		model/code.cpp \
		view/codeList.cpp \
		view/codeSettings.cpp \
		view/documentList.cpp \
		view/fastqda.cpp \
		view/mainWidget.cpp moc_codeList.cpp \
		moc_codeSettings.cpp \
		moc_documentList.cpp \
		moc_fastqda.cpp \
		moc_mainWidget.cpp
OBJECTS       = main.o \
		codeManager.o \
		code.o \
		codeList.o \
		codeSettings.o \
		documentList.o \
		fastqda.o \
		mainWidget.o \
		moc_codeList.o \
		moc_codeSettings.o \
		moc_documentList.o \
		moc_fastqda.o \
		moc_mainWidget.o
DIST          = ../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.3/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.3/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.3/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.3/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.3/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.3/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.3/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.3/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.3/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.3/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.3/clang_64/mkspecs/features/lex.prf \
		fastQDA.pro main.cpp \
		control/codeManager.cpp \
		model/code.cpp \
		view/codeList.cpp \
		view/codeSettings.cpp \
		view/documentList.cpp \
		view/fastqda.cpp \
		view/mainWidget.cpp
QMAKE_TARGET  = fastQDA
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = fastQDA.app/Contents/MacOS/fastQDA

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile fastQDA.app/Contents/PkgInfo fastQDA.app/Contents/Resources/empty.lproj fastQDA.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d fastQDA.app/Contents/MacOS/ || mkdir -p fastQDA.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: fastQDA.pro ../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.3/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.3/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.3/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.3/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.3/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.3/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.3/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.3/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.3/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.3/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.3/clang_64/mkspecs/features/lex.prf \
		fastQDA.pro \
		/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile fastQDA.pro
../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.3/clang_64/mkspecs/qdevice.pri:
../../Qt/5.3/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf:
../../Qt/5.3/clang_64/mkspecs/common/unix.conf:
../../Qt/5.3/clang_64/mkspecs/common/mac.conf:
../../Qt/5.3/clang_64/mkspecs/common/macx.conf:
../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.3/clang_64/mkspecs/common/clang.conf:
../../Qt/5.3/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.3/clang_64/mkspecs/qconfig.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.3/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.3/clang_64/mkspecs/features/qt.prf:
../../Qt/5.3/clang_64/mkspecs/features/resources.prf:
../../Qt/5.3/clang_64/mkspecs/features/moc.prf:
../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.3/clang_64/mkspecs/features/uic.prf:
../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.3/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.3/clang_64/mkspecs/features/lex.prf:
fastQDA.pro:
/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile fastQDA.pro

qmake_all: FORCE

fastQDA.app/Contents/PkgInfo: 
	@test -d fastQDA.app/Contents || mkdir -p fastQDA.app/Contents
	@$(DEL_FILE) fastQDA.app/Contents/PkgInfo
	@echo "APPL????" >fastQDA.app/Contents/PkgInfo
fastQDA.app/Contents/Resources/empty.lproj: 
	@test -d fastQDA.app/Contents/Resources || mkdir -p fastQDA.app/Contents/Resources
	@touch fastQDA.app/Contents/Resources/empty.lproj
	
fastQDA.app/Contents/Info.plist: 
	@test -d fastQDA.app/Contents || mkdir -p fastQDA.app/Contents
	@$(DEL_FILE) fastQDA.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.fastQDA,g" -e "s,@EXECUTABLE@,fastQDA,g" -e "s,@TYPEINFO@,????,g" ../../Qt/5.3/clang_64/mkspecs/macx-clang/Info.plist.app >fastQDA.app/Contents/Info.plist
dist: 
	@test -d .tmp/fastQDA1.0.0 || mkdir -p .tmp/fastQDA1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/fastQDA1.0.0/ && $(COPY_FILE) --parents control/codeManager.h model/code.h view/codeList.h view/codeSettings.h view/documentList.h view/fastqda.h view/mainWidget.h .tmp/fastQDA1.0.0/ && $(COPY_FILE) --parents main.cpp control/codeManager.cpp model/code.cpp view/codeList.cpp view/codeSettings.cpp view/documentList.cpp view/fastqda.cpp view/mainWidget.cpp .tmp/fastQDA1.0.0/ && (cd `dirname .tmp/fastQDA1.0.0` && $(TAR) fastQDA1.0.0.tar fastQDA1.0.0 && $(COMPRESS) fastQDA1.0.0.tar) && $(MOVE) `dirname .tmp/fastQDA1.0.0`/fastQDA1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/fastQDA1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r fastQDA.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_codeList.cpp moc_codeSettings.cpp moc_documentList.cpp moc_fastqda.cpp moc_mainWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_codeList.cpp moc_codeSettings.cpp moc_documentList.cpp moc_fastqda.cpp moc_mainWidget.cpp
moc_codeList.cpp: ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		control/codeManager.h \
		model/code.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		view/codeList.h
	/Users/michaelriedel/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/michaelriedel/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/michaelriedel/Developer/fastQDA -I/Users/michaelriedel/Developer/fastQDA -I/Users/michaelriedel/Developer/fastQDA/view -I/Users/michaelriedel/Developer/fastQDA/control -I/Users/michaelriedel/Developer/fastQDA/model -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/michaelriedel/Qt/5.3/clang_64/lib view/codeList.h -o moc_codeList.cpp

moc_codeSettings.cpp: ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPlainTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QComboBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidgetItem \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		view/codeSettings.h
	/Users/michaelriedel/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/michaelriedel/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/michaelriedel/Developer/fastQDA -I/Users/michaelriedel/Developer/fastQDA -I/Users/michaelriedel/Developer/fastQDA/view -I/Users/michaelriedel/Developer/fastQDA/control -I/Users/michaelriedel/Developer/fastQDA/model -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/michaelriedel/Qt/5.3/clang_64/lib view/codeSettings.h -o moc_codeSettings.cpp

moc_documentList.cpp: ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		view/documentList.h
	/Users/michaelriedel/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/michaelriedel/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/michaelriedel/Developer/fastQDA -I/Users/michaelriedel/Developer/fastQDA -I/Users/michaelriedel/Developer/fastQDA/view -I/Users/michaelriedel/Developer/fastQDA/control -I/Users/michaelriedel/Developer/fastQDA/model -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/michaelriedel/Qt/5.3/clang_64/lib view/documentList.h -o moc_documentList.cpp

moc_fastqda.cpp: ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDockWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidgetItem \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		view/documentList.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidget \
		view/mainWidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QHBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		view/codeList.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		control/codeManager.h \
		model/code.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		view/fastqda.h
	/Users/michaelriedel/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/michaelriedel/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/michaelriedel/Developer/fastQDA -I/Users/michaelriedel/Developer/fastQDA -I/Users/michaelriedel/Developer/fastQDA/view -I/Users/michaelriedel/Developer/fastQDA/control -I/Users/michaelriedel/Developer/fastQDA/model -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/michaelriedel/Qt/5.3/clang_64/lib view/fastqda.h -o moc_fastqda.cpp

moc_mainWidget.cpp: ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QHBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidgetItem \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		view/mainWidget.h
	/Users/michaelriedel/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/michaelriedel/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/michaelriedel/Developer/fastQDA -I/Users/michaelriedel/Developer/fastQDA -I/Users/michaelriedel/Developer/fastQDA/view -I/Users/michaelriedel/Developer/fastQDA/control -I/Users/michaelriedel/Developer/fastQDA/model -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/michaelriedel/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/michaelriedel/Qt/5.3/clang_64/lib view/mainWidget.h -o moc_mainWidget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp view/fastqda.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDockWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidgetItem \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		view/documentList.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidget \
		view/mainWidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QHBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		view/codeList.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		control/codeManager.h \
		model/code.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

codeManager.o: control/codeManager.cpp ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		control/codeManager.h \
		model/code.h \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o codeManager.o control/codeManager.cpp

code.o: model/code.cpp model/code.h \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o code.o model/code.cpp

codeList.o: view/codeList.cpp view/codeList.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		control/codeManager.h \
		model/code.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		view/codeSettings.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPlainTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QComboBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidgetItem \
		view/fastqda.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDockWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		view/documentList.h \
		view/mainWidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QHBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o codeList.o view/codeList.cpp

codeSettings.o: view/codeSettings.cpp ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QHBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QColorDialog \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolordialog.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QFontMetrics \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontmetrics.h \
		view/codeSettings.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPlainTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QComboBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidgetItem \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		view/codeList.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidget \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		control/codeManager.h \
		model/code.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o codeSettings.o view/codeSettings.cpp

documentList.o: view/documentList.cpp view/documentList.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o documentList.o view/documentList.cpp

fastqda.o: view/fastqda.cpp ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QHeaderView \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qheaderview.h \
		view/fastqda.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDockWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidgetItem \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		view/documentList.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidget \
		view/mainWidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QHBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		view/codeList.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		control/codeManager.h \
		model/code.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fastqda.o view/fastqda.cpp

mainWidget.o: view/mainWidget.cpp ../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QTextCursor \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextcursor.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QTextCharFormat \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextformat.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QBrush \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qbrush.h \
		view/mainWidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QHBoxLayout \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTextEdit \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidgetItem \
		../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainWidget.o view/mainWidget.cpp

moc_codeList.o: moc_codeList.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_codeList.o moc_codeList.cpp

moc_codeSettings.o: moc_codeSettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_codeSettings.o moc_codeSettings.cpp

moc_documentList.o: moc_documentList.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_documentList.o moc_documentList.cpp

moc_fastqda.o: moc_fastqda.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fastqda.o moc_fastqda.cpp

moc_mainWidget.o: moc_mainWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainWidget.o moc_mainWidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

